services:
  app:
    build:
      context: ./docker/php
    container_name: laravel_admin_app
    working_dir: /var/www/html
    volumes:
      - ./myapp:/var/www/html

  web:
    image: nginx:alpine
    container_name: laravel_admin_nginx
    ports:
      - "8000:80"
    volumes:
      - ./myapp:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
  node:
    image: node:20
    container_name: laravel_admin_node
    working_dir: /var/www/html
    volumes:
      - ./myapp:/var/www/html
    command: sh -c "npm install && npm run build"
